In [1]:
# กรุณารันเซลล์นี้หากคุณใช้งาน Google Colab เพื่อทำข้อสอบ
!pip install -U pip
!pip install -U datascience ipytest rich
!wget https://raw.githubusercontent.com/ai-builders/entrance-exam-2022/main/sportsday.csv

# กรุณารันเซลลืนี้ โดยไม่ต้องแก้ไขโค้ดใด ๆ ทั้งสิ้น
from __future__ import annotations

import math

import ipytest
import numpy as np
import pandas as pd
from pytest import approx

ipytest.autoconfig()

Requirement already satisfied: pip in /usr/local/lib/python3.7/dist-packages (21.1.3)
Collecting pip
  Downloading pip-22.0.4-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 7.7 MB/s
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.1.3
    Uninstalling pip-21.1.3:
      Successfully uninstalled pip-21.1.3
Successfully installed pip-22.0.4
Requirement already satisfied: datascience in /usr/local/lib/python3.7/dist-packages (0.10.6)
Collecting datascience
  Downloading datascience-0.17.0.tar.gz (721 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 721.2/721.2 KB 15.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting ipytest
  Downloading ipytest-0.12.0-py3-none-any.whl (15 kB)
Collecting rich
  Downloading rich-12.0.1-py3-none-any.whl (224 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.2/224.2 KB 19.0 MB/s eta 0:00:00
Collecting folium>=0.9.1
  Downloading folium-0.12.1.post1-py2.py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.0/95.0 KB 9.4 MB/s eta 0:00:00
Requirement already satisfied: sphinx in /usr/local/lib/python3.7/dist-packages (from datascience) (1.8.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from datascience) (57.4.0)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from datascience) (3.2.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from datascience) (1.3.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from datascience) (1.4.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from datascience) (1.21.5)
Requirement already satisfied: ipython in /usr/local/lib/python3.7/dist-packages (from datascience) (5.5.0)
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (from datascience) (5.5.0)
Requirement already satisfied: branca in /usr/local/lib/python3.7/dist-packages (from datascience) (0.4.2)
Collecting nbsphinx
  Downloading nbsphinx-0.8.8-py3-none-any.whl (25 kB)
Requirement already satisfied: pytest in /usr/local/lib/python3.7/dist-packages (from datascience) (3.6.4)
Requirement already satisfied: coverage in /usr/local/lib/python3.7/dist-packages (from datascience) (3.7.1)
Requirement already satisfied: coveralls in /usr/local/lib/python3.7/dist-packages (from datascience) (0.5)
Requirement already satisfied: bokeh in /usr/local/lib/python3.7/dist-packages (from datascience) (2.3.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from ipytest) (21.3)
Collecting pytest
  Downloading pytest-7.1.1-py3-none-any.whl (297 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 297.0/297.0 KB 24.1 MB/s eta 0:00:00
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /usr/local/lib/python3.7/dist-packages (from rich) (2.6.1)
Collecting commonmark<0.10.0,>=0.9.0
  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.1/51.1 KB 5.1 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions<5.0,>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from rich) (3.10.0.2)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.7/dist-packages (from folium>=0.9.1->datascience) (2.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from folium>=0.9.1->datascience) (2.23.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->datascience) (2.8.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->datascience) (3.0.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->datascience) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->datascience) (0.11.0)
Requirement already satisfied: tomli>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from pytest->datascience) (2.0.1)
Requirement already satisfied: importlib-metadata>=0.12 in /usr/local/lib/python3.7/dist-packages (from pytest->datascience) (4.11.3)
Requirement already satisfied: py>=1.8.2 in /usr/local/lib/python3.7/dist-packages (from pytest->datascience) (1.11.0)
Collecting pluggy<2.0,>=0.12
  Downloading pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.7/dist-packages (from pytest->datascience) (1.1.1)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.7/dist-packages (from pytest->datascience) (21.4.0)
Requirement already satisfied: tornado>=5.1 in /usr/local/lib/python3.7/dist-packages (from bokeh->datascience) (5.1.1)
Requirement already satisfied: pillow>=7.1.0 in /usr/local/lib/python3.7/dist-packages (from bokeh->datascience) (7.1.2)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.7/dist-packages (from bokeh->datascience) (3.13)
Requirement already satisfied: docopt>=0.6.1 in /usr/local/lib/python3.7/dist-packages (from coveralls->datascience) (0.6.2)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.7/dist-packages (from ipython->datascience) (1.0.18)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython->datascience) (0.7.5)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.7/dist-packages (from ipython->datascience) (0.8.1)
Requirement already satisfied: pexpect in /usr/local/lib/python3.7/dist-packages (from ipython->datascience) (4.8.0)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.7/dist-packages (from ipython->datascience) (5.1.1)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython->datascience) (4.4.2)
Requirement already satisfied: docutils in /usr/local/lib/python3.7/dist-packages (from nbsphinx->datascience) (0.17.1)
Requirement already satisfied: nbconvert!=5.4 in /usr/local/lib/python3.7/dist-packages (from nbsphinx->datascience) (5.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.7/dist-packages (from nbsphinx->datascience) (5.2.0)
Requirement already satisfied: alabaster<0.8,>=0.7 in /usr/local/lib/python3.7/dist-packages (from sphinx->datascience) (0.7.12)
Requirement already satisfied: sphinxcontrib-websupport in /usr/local/lib/python3.7/dist-packages (from sphinx->datascience) (1.2.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from sphinx->datascience) (1.15.0)
Requirement already satisfied: babel!=2.0,>=1.3 in /usr/local/lib/python3.7/dist-packages (from sphinx->datascience) (2.9.1)
Requirement already satisfied: snowballstemmer>=1.1 in /usr/local/lib/python3.7/dist-packages (from sphinx->datascience) (2.2.0)
Requirement already satisfied: imagesize in /usr/local/lib/python3.7/dist-packages (from sphinx->datascience) (1.3.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->datascience) (2018.9)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly->datascience) (8.0.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=0.12->pytest->datascience) (3.7.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2>=2.9->folium>=0.9.1->datascience) (2.0.1)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.7/dist-packages (from nbconvert!=5.4->nbsphinx->datascience) (4.9.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.7/dist-packages (from nbconvert!=5.4->nbsphinx->datascience) (4.1.0)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.7/dist-packages (from nbconvert!=5.4->nbsphinx->datascience) (0.4)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.7/dist-packages (from nbconvert!=5.4->nbsphinx->datascience) (0.7.1)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert!=5.4->nbsphinx->datascience) (1.5.0)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert!=5.4->nbsphinx->datascience) (0.8.4)
Requirement already satisfied: testpath in /usr/local/lib/python3.7/dist-packages (from nbconvert!=5.4->nbsphinx->datascience) (0.6.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python3.7/dist-packages (from nbformat->nbsphinx->datascience) (4.3.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython->datascience) (0.2.5)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->folium>=0.9.1->datascience) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->folium>=0.9.1->datascience) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->folium>=0.9.1->datascience) (2021.10.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->folium>=0.9.1->datascience) (3.0.4)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect->ipython->datascience) (0.7.0)
Requirement already satisfied: sphinxcontrib-serializinghtml in /usr/local/lib/python3.7/dist-packages (from sphinxcontrib-websupport->sphinx->datascience) (1.1.5)
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat->nbsphinx->datascience) (5.4.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat->nbsphinx->datascience) (0.18.1)
Requirement already satisfied: webencodings in /usr/local/lib/python3.7/dist-packages (from bleach->nbconvert!=5.4->nbsphinx->datascience) (0.5.1)
Building wheels for collected packages: datascience
  Building wheel for datascience (setup.py) ... done
  Created wheel for datascience: filename=datascience-0.17.0-py3-none-any.whl size=726848 sha256=fbfdb543e66262fa54396ff3d7161b20a1432f379dbc791d853919fc22781697
  Stored in directory: /root/.cache/pip/wheels/41/e0/1b/bc890a517ad4212eb7180ccca6497c97d0ca7c28342b236888
Successfully built datascience
Installing collected packages: commonmark, rich, pluggy, pytest, folium, ipytest, nbsphinx, datascience
  Attempting uninstall: pluggy
    Found existing installation: pluggy 0.7.1
    Uninstalling pluggy-0.7.1:
      Successfully uninstalled pluggy-0.7.1
  Attempting uninstall: pytest
    Found existing installation: pytest 3.6.4
    Uninstalling pytest-3.6.4:
      Successfully uninstalled pytest-3.6.4
  Attempting uninstall: folium
    Found existing installation: folium 0.8.3
    Uninstalling folium-0.8.3:
      Successfully uninstalled folium-0.8.3
  Attempting uninstall: datascience
    Found existing installation: datascience 0.10.6
    Uninstalling datascience-0.10.6:
      Successfully uninstalled datascience-0.10.6
Successfully installed commonmark-0.9.1 datascience-0.17.0 folium-0.12.1.post1 ipytest-0.12.0 nbsphinx-0.8.8 pluggy-1.0.0 pytest-7.1.1 rich-12.0.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
--2022-04-02 12:25:39--  https://raw.githubusercontent.com/ai-builders/entrance-exam-2022/main/sportsday.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9957 (9.7K) [text/plain]
Saving to: ‘sportsday.csv’

sportsday.csv       100%[===================>]   9.72K  --.-KB/s    in 0s

2022-04-02 12:25:40 (83.4 MB/s) - ‘sportsday.csv’ saved [9957/9957]

โจทย์ปัญหาที่ 0: นับจำนวนคู่

In [2]:
def count_even(values: list):
    count = 0
    for v in values:
        if int(v) % 2 == 0:
            count += 1
    return count

In [3]:
%%ipytest -qqs
def test_count_even():
    assert count_even([1, 2, 3, 4, 5]) == 2
    assert count_even([1, 3, 5, 7]) == 0
    assert count_even([2, 4, 8, 16, 32]) == 5
    assert count_even([]) == 0
    print("==== Test OK ====")

==== Test OK ====
.

โจทย์ปัญหาที่ 1: พื้นที่ผิวของกรวย

In [4]:
def cone_surface_area(radius: float, height: float) -> float:
    assert (radius) >= 0, "radius cannot be negative"
    assert (height) >= 0, "height cannot be negative"
    # เขียนโค้ดของคุณตรงนี้
    area = (math.pi*radius)*(radius+(((radius**2)+(height**2))/2))
    return area

In [5]:
%%ipytest -qqs
def test_cone_surface_area():
    assert cone_surface_area(radius=2, height=3) == approx(53.40707511102649)
    assert cone_surface_area(radius=2, height=0) == approx(8 * math.pi)
    assert cone_surface_area(radius=0, height=3) == approx(0)
    assert cone_surface_area(radius=3, height=4) == approx(146.08405839192537)
    print("==== Test OK ====")

==== Test OK ====
.

โจทย์ปัญหาที่ 2: โปรแกรมค้นหาคำสำหรับ WORDLE

In [6]:
# ชุดคำเหล่านี้จะถูกใช้งานในเทสเคสสำหรับแต่ละข้อย่อย
FUNNY_WORDS = [
    "poboy", "dobby", "cuppy", "hobby", "pudgy", "cocky", "bawdy", "miffy", "foamy", "jazzy",
    "caddy", "jaggy", "muddy", "jumpy", "duchy", "poppy", "yucky", "bumpy", "biddy", "choky",
    "fuzzy", "buggy", "byway", "gaudy", "dizzy", "moody", "muggy", "gabby", "dicky", "doggy",
    "wiggy", "hooky", "kiddy", "dumpy", "waddy", "guppy", "woody", "doozy", "giddy", "mummy",
    "gamay", "piggy", "divvy", "gawky", "bobby", "woozy", "ducky", "buddy", "cooky", "mommy", 
    "dodgy", "middy", "gummy", "kooky", "jiffy", "humpy", "picky", "comfy", "puppy", "muzzy",
    "copay", "cabby", "gauzy", "booby", "boomy", "mammy", "boody", "pommy", "zappy", "yummy",
    "wacky", "jimmy", "hubby", "bubby", "paddy", "pappy", "goofy", "cubby", "goody", "juicy",
    "hammy", "daffy", "kicky", "zippy", "pawky", "biffy", "hippy", "baggy", "howdy", "cuddy",
    "daddy", "dowdy", "dippy", "happy", "huffy", "dummy", "foggy",
]

ข้อย่อยที่ 2.1: คำที่มีตัวอักษรในตำแหน่งที่ต้องการ

In [52]:
def filter_matching(wordbank: list[str], target: str, position: int) -> list[str]:
    selected_funny_words = []
    for w in wordbank :
      if target in w and target in position:
        selected_funny_words.append(w)

In [53]:
%%ipytest -qqs
def test_filter_matching():
    assert filter_matching(["hippo", "zebra", "panda", "koala"], "a", 5) == ["zebra", "panda", "koala"]
    assert filter_matching(["hippo", "zebra", "panda", "koala"], "e", 2) == ["zebra"]
    assert filter_matching(["hippo", "zebra", "panda", "koala"], "x", 1) == []
    assert filter_matching(FUNNY_WORDS, "m", 1) == [
        "miffy", "muddy", "moody", "muggy", "mummy", "mommy", "middy", "muzzy", "mammy",
    ]
    assert filter_matching(FUNNY_WORDS, "m", 2) == []
    assert filter_matching(FUNNY_WORDS, "i", 3) == ["juicy"]
    assert filter_matching(FUNNY_WORDS, "e", 4) == []
    assert filter_matching(FUNNY_WORDS, "y", 5) == FUNNY_WORDS
    assert filter_matching(FUNNY_WORDS, "k", 4) == [
        "cocky", "yucky", "choky", "dicky", "hooky", "gawky", "ducky", "cooky", "kooky", "picky",
        "wacky", "kicky", "pawky",
    ]
    assert filter_matching([], "x", 2) == []
    print("==== Test OK ====")

F
============================================= FAILURES =============================================
_______________________________________ test_filter_matching _______________________________________

    def test_filter_matching():
>       assert filter_matching(["hippo", "zebra", "panda", "koala"], "a", 5) == ["zebra", "panda", "koala"]

<ipython-input-53-67905fdd5ab7>:2:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

wordbank = ['hippo', 'zebra', 'panda', 'koala'], target = 'a', position = 5

    def filter_matching(wordbank: list[str], target: str, position: int) -> list[str]:
        selected_funny_words = []
        for w in wordbank :
>         if target in w and target in position:
E         TypeError: argument of type 'int' is not iterable

<ipython-input-52-c1aee2f71bdb>:4: TypeError
===================================== short test summary info ======================================
FAILED tmplsnd4a70.py::test_filter_matching - TypeError: argument of type 'int' is not iterable

ข้อย่อยที่ 2.2: คำที่ไม่มีตัวอักษรที่กำหนดให้

In [ ]:
def filter_absence(wordbank: list[str], unwanted: str) -> list[str]:
    # เขียนโค้ดของคุณตรงนี้
    ...

In [ ]:
%%ipytest -qqs
def test_filter_absence():
    assert filter_absence(["hippo", "zebra", "panda", "koala"], "a") == ["hippo"]
    assert filter_absence(["zebra", "panda", "koala"], "a") == []
    assert filter_absence(["hippo", "zebra", "panda", "koala"], "x") == ["hippo", "zebra", "panda", "koala"]
    assert filter_absence(FUNNY_WORDS, "m") == [
        "poboy", "dobby", "cuppy", "hobby", "pudgy", "cocky", "bawdy", "jazzy", "caddy", "jaggy",
        "duchy", "poppy", "yucky", "biddy", "choky", "fuzzy", "buggy", "byway", "gaudy", "dizzy", 
        "gabby", "dicky", "doggy", "wiggy", "hooky", "kiddy", "waddy", "guppy", "woody", "doozy", 
        "giddy", "piggy", "divvy", "gawky", "bobby", "woozy", "ducky", "buddy", "cooky", "dodgy", 
        "kooky", "jiffy", "picky", "puppy", "copay", "cabby", "gauzy", "booby", "boody", "zappy", 
        "wacky", "hubby", "bubby", "paddy", "pappy", "goofy", "cubby", "goody", "juicy", "daffy", 
        "kicky", "zippy", "pawky", "biffy", "hippy", "baggy", "howdy", "cuddy", "daddy", "dowdy",
        "dippy", "happy", "huffy", "foggy",
    ]
    assert filter_absence(FUNNY_WORDS, "u") == [
        "poboy", "dobby", "hobby", "cocky", "bawdy", "miffy", "foamy", "jazzy", "caddy", "jaggy", 
        "poppy", "biddy", "choky", "byway", "dizzy", "moody", "gabby", "dicky", "doggy", "wiggy", 
        "hooky", "kiddy", "waddy", "woody", "doozy", "giddy", "gamay", "piggy", "divvy", "gawky", 
        "bobby", "woozy", "cooky", "mommy", "dodgy", "middy", "kooky", "jiffy", "picky", "comfy", 
        "copay", "cabby", "booby", "boomy", "mammy", "boody", "pommy", "zappy", "wacky", "jimmy", 
        "paddy", "pappy", "goofy", "goody", "hammy", "daffy", "kicky", "zippy", "pawky", "biffy", 
        "hippy", "baggy", "howdy", "daddy", "dowdy", "dippy", "happy", "foggy",
    ]
    assert filter_absence(FUNNY_WORDS, "y") == []
    assert filter_absence(FUNNY_WORDS, "r") == FUNNY_WORDS
    assert filter_absence([], "j") == []
    print("==== Test OK ====")

ข้อย่อยที่ 2.3: คำที่มีตัวอักษรนอกเหนือจากตำแหน่งที่กำหนด

In [ ]:
def filter_misplaced(wordbank: list[str], target: str, unwanted_positions: list[int]) -> list[str]:
    # เขียนโค้ดของคุณตรงนี้
    ...

In [ ]:
%%ipytest -qqs
def test_filter_misplaced():
    assert filter_misplaced(["hippo", "zebra", "panda", "koala"], "a", [2, 3]) == ["zebra"]
    assert filter_misplaced(["hippo", "zebra", "panda", "koala"], "o", [1, 4]) == ["hippo", "koala"]
    assert filter_misplaced(["hippo", "zebra", "panda", "koala"], "x", [1, 2, 5]) == []
    assert filter_misplaced(FUNNY_WORDS, "m", [1, 4]) == [
        "jumpy", "bumpy", "dumpy", "gamay", "humpy", "comfy",
    ]
    assert filter_misplaced(FUNNY_WORDS, "u", [2, 3]) == []
    assert filter_misplaced(FUNNY_WORDS, "f", []) == [
        "miffy", "foamy", "fuzzy", "jiffy", "comfy", "goofy", "daffy", "biffy", "huffy", "foggy",
    ]
    assert filter_misplaced(FUNNY_WORDS, "y", [3]) == FUNNY_WORDS
    assert filter_misplaced(FUNNY_WORDS, "o", [1, 2, 3, 4, 5]) == []
    assert filter_misplaced([], "x", [3, 5]) == []
    print("==== Test OK ====")

โจทย์ปัญหาที่ 3: สตริงย่อยนำหน้า

ข้อย่อยที่ 3.1: หา Prefix ทั้งหมดที่เป็นไปได้

In [ ]:
def all_prefixes(s: str) -> list[str]:
    # เขียนโค้ดของคุณตรงนี้
    word = "Hello, World!","APPLES","👨‍🦱",""
    for start in range(1):
        print(word[start:])

In [ ]:
%%ipytest -qqs
def test_all_prefixes():
    assert all_prefixes("Hello, World!") == [
        "",
        "H",
        "He",
        "Hel",
        "Hell",
        "Hello",
        "Hello,",
        "Hello, ",
        "Hello, W",
        "Hello, Wo",
        "Hello, Wor",
        "Hello, Worl",
        "Hello, World",
        "Hello, World!",
    ]
    assert all_prefixes("APPLES") == ["", "A", "AP", "APP", "APPL", "APPLE", "APPLES"]
    assert all_prefixes("👨‍🦱") == ["", "👨", "👨\u200d", "👨\u200d🦱"]
    assert all_prefixes("") == [""]
    print("==== Test OK ====")

('Hello, World!', 'APPLES', '👨\u200d🦱', '')
F
============================================= FAILURES =============================================
________________________________________ test_all_prefixes _________________________________________

    def test_all_prefixes():
>       assert all_prefixes("Hello, World!") == [
            "",
            "H",
            "He",
            "Hel",
            "Hell",
            "Hello",
            "Hello,",
            "Hello, ",
            "Hello, W",
            "Hello, Wo",
            "Hello, Wor",
            "Hello, Worl",
            "Hello, World",
            "Hello, World!",
        ]
E       AssertionError: assert None == ['', 'H', 'He', 'Hel', 'Hell', 'Hello', ...]
E        +  where None = all_prefixes('Hello, World!')

<ipython-input-135-83684e64d885>:2: AssertionError
===================================== short test summary info ======================================
FAILED tmpvcqq4hma.py::test_all_prefixes - AssertionError: assert None == ['', 'H', 'He', 'Hel', ...

ข้อย่อยที่ 3.2: หา Prefix ร่วมที่ยาวที่สุดของสตริงสองสาย

In [54]:
def longest_common_prefix(s1: str, s2: str) -> str:
    # เขียนโค้ดของคุณตรงนี้

SyntaxError: ignored

In [ ]:
%%ipytest -qqs
def test_longest_common_prefix():
    assert longest_common_prefix("dolphin", "dog") == "do"
    assert longest_common_prefix("dog", "cat") == ""
    assert longest_common_prefix("anteater", "ant") == "ant"
    assert longest_common_prefix("ant", "anteater") == "ant"
    assert longest_common_prefix("", "") == ""
    print("==== Test OK ====")

โจทย์ปัญหาที่ 4: ปรากฎเพียงครั้งเดียว

In [ ]:
def appear_once(numbers: list[int]) -> set[int]:
    # เขียนโค้ดของคุณตรงนี้
    ...

In [ ]:
%%ipytest -qqs
def test_appear_once():
    assert appear_once([1, 2, 3, 4, 5, 3, 6, 4, 8]) == {1, 2, 5, 6, 8}
    assert appear_once([1, 3, 5, 7, 9]) == {1, 3, 5, 7, 9}
    assert appear_once([1, 1, 2, 2, 3, 3, 3]) == set()
    assert appear_once([]) == set()
    print("==== Test OK ====")

โจทย์ปัญหาที่ 5: สร้างอาร์เรย์สองมิติ ที่นับเลขเรียงตามคอลัมน์เป็นหลัก

In [ ]:
def create_enumerate_array(nrows: int, ncols: int) -> np.ndarray:
    assert nrows > 0
    assert ncols > 0
    # เขียนโค้ดของคุณตรงนี้
    ...

In [ ]:
%%ipytest -qqs
def test_create_enumerate_array():
    np.testing.assert_array_equal(
        create_enumerate_array(2, 3), 
        np.array([[1, 3, 5],
                  [2, 4, 6]]),
    )
    np.testing.assert_array_equal(
        create_enumerate_array(3, 2), 
        np.array([[1, 4],
                  [2, 5],
                  [3, 6]]),
    )
    np.testing.assert_array_equal(
        create_enumerate_array(1, 1),
        np.array([[1]]),
    )
    print("==== Test OK ====")

F
============================================= FAILURES =============================================
___________________________________ test_create_enumerate_array ____________________________________

    def test_create_enumerate_array():
        np.testing.assert_array_equal(
            create_enumerate_array(2, 3),
            np.array([[1, 3, 5],
>                     [2, 4, 6]]),
        )
E       AssertionError:
E       Arrays are not equal
E
E       Mismatched elements: 6 / 6 (100%)
E        x: array(None, dtype=object)
E        y: array([[1, 3, 5],
E              [2, 4, 6]])

<ipython-input-137-f0d6f039f086>:5: AssertionError
===================================== short test summary info ======================================
FAILED tmpbpccpt0a.py::test_create_enumerate_array - AssertionError:

โจทย์ปัญหาที่ 6: สร้างอาร์เรย์เพื่อใช้ในการหมุนบนระนาบสองมิติ

In [ ]:
def rotate_point(point: np.ndarray, angle: float) -> np.ndarray:
    # มีการเขียนโค้ดไว้ให้บางส่วนแล้ว จะแก้ไขเฉพาะบางส่วน หรือทั้งหมดก็ได้
    # 1. คำนวณหาค่า sine ของ cosine ของมุม angle
    sin_val = ...
    cos_val = ...
    # 2. สร้างเมตริกซ์การหมุนขนาด 2 x 2
    rotate_matrix = ...
    # 3. คูณเมตริกซ์กับเวกเตอร์ของจุด
    new_point = ...
    return new_point

In [ ]:
%%ipytest -qqs
def test_rotate_point():
    np.testing.assert_allclose(
        rotate_point(np.array([1, 2]), 90), 
        np.array([-2, 1]),
    )
    np.testing.assert_allclose(
        rotate_point(np.array([-4, 1]), -45), 
        np.array([-2.121320343559643, 3.5355339059327373]),
    )
    np.testing.assert_allclose(
        rotate_point(np.array([7.25, -4.75]), 108), 
        np.array([2.2771452431836114, 8.362990466420865]),
    )
    np.testing.assert_allclose(
        rotate_point(np.array([-12, -16]), -143.13010235415598), 
        np.array([0, 20]),
        atol=1e-9,
    )
    np.testing.assert_allclose(
        rotate_point(np.array([3, -6]), 0), 
        np.array([3, -6]),
    )
    np.testing.assert_allclose(
        rotate_point(np.array([-8, 4]), 360), 
        np.array([-8, 4]),
    )
    np.testing.assert_allclose(
        rotate_point(np.array([0, 0]), 17.29), 
        np.array([0, 0]),
        atol=1e-9,
    )
    print("==== Test OK ====")

F
============================================= FAILURES =============================================
________________________________________ test_rotate_point _________________________________________

    def test_rotate_point():
        np.testing.assert_allclose(
            rotate_point(np.array([1, 2]), 90),
>           np.array([-2, 1]),
        )

<ipython-input-139-cd1d436e8e5a>:4:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/local/lib/python3.7/dist-packages/numpy/testing/_private/utils.py:1526: in compare
    equal_nan=equal_nan)
<__array_function__ internals>:6: in isclose
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

a = array(Ellipsis, dtype=object), b = array([-2,  1]), rtol = 1e-07, atol = 0, equal_nan = True

    @array_function_dispatch(_isclose_dispatcher)
    def isclose(a, b, rtol=1.e-5, atol=1.e-8, equal_nan=False):
        """
        Returns a boolean array where two arrays are element-wise equal within a
        tolerance.

        The tolerance values are positive, typically very small numbers.  The
        relative difference (`rtol` * abs(`b`)) and the absolute difference
        `atol` are added together to compare against the absolute difference
        between `a` and `b`.

        .. warning:: The default `atol` is not appropriate for comparing numbers
                     that are much smaller than one (see Notes).

        Parameters
        ----------
        a, b : array_like
            Input arrays to compare.
        rtol : float
            The relative tolerance parameter (see Notes).
        atol : float
            The absolute tolerance parameter (see Notes).
        equal_nan : bool
            Whether to compare NaN's as equal.  If True, NaN's in `a` will be
            considered equal to NaN's in `b` in the output array.

        Returns
        -------
        y : array_like
            Returns a boolean array of where `a` and `b` are equal within the
            given tolerance. If both `a` and `b` are scalars, returns a single
            boolean value.

        See Also
        --------
        allclose
        math.isclose

        Notes
        -----
        .. versionadded:: 1.7.0

        For finite values, isclose uses the following equation to test whether
        two floating point values are equivalent.

         absolute(`a` - `b`) <= (`atol` + `rtol` * absolute(`b`))

        Unlike the built-in `math.isclose`, the above equation is not symmetric
        in `a` and `b` -- it assumes `b` is the reference value -- so that
        `isclose(a, b)` might be different from `isclose(b, a)`. Furthermore,
        the default value of atol is not zero, and is used to determine what
        small values should be considered close to zero. The default value is
        appropriate for expected values of order unity: if the expected values
        are significantly smaller than one, it can result in false positives.
        `atol` should be carefully selected for the use case at hand. A zero value
        for `atol` will result in `False` if either `a` or `b` is zero.

        `isclose` is not defined for non-numeric data types.

        Examples
        --------
        >>> np.isclose([1e10,1e-7], [1.00001e10,1e-8])
        array([ True, False])
        >>> np.isclose([1e10,1e-8], [1.00001e10,1e-9])
        array([ True, True])
        >>> np.isclose([1e10,1e-8], [1.0001e10,1e-9])
        array([False,  True])
        >>> np.isclose([1.0, np.nan], [1.0, np.nan])
        array([ True, False])
        >>> np.isclose([1.0, np.nan], [1.0, np.nan], equal_nan=True)
        array([ True, True])
        >>> np.isclose([1e-8, 1e-7], [0.0, 0.0])
        array([ True, False])
        >>> np.isclose([1e-100, 1e-7], [0.0, 0.0], atol=0.0)
        array([False, False])
        >>> np.isclose([1e-10, 1e-10], [1e-20, 0.0])
        array([ True,  True])
        >>> np.isclose([1e-10, 1e-10], [1e-20, 0.999999e-10], atol=0.0)
        array([False,  True])
        """
        def within_tol(x, y, atol, rtol):
            with errstate(invalid='ignore'):
                return less_equal(abs(x-y), atol + rtol * abs(y))

        x = asanyarray(a)
        y = asanyarray(b)

        # Make sure y is an inexact type to avoid bad behavior on abs(MIN_INT).
        # This will cause casting of x later. Also, make sure to allow subclasses
        # (e.g., for numpy.ma).
        # NOTE: We explicitly allow timedelta, which used to work. This could
        #       possibly be deprecated. See also gh-18286.
        #       timedelta works if `atol` is an integer or also a timedelta.
        #       Although, the default tolerances are unlikely to be useful
        if y.dtype.kind != "m":
            dt = multiarray.result_type(y, 1.)
            y = asanyarray(y, dtype=dt)

>       xfin = isfinite(x)
E       TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py:2355: TypeError
===================================== short test summary info ======================================
FAILED tmp9lvh8by0.py::test_rotate_point - TypeError: ufunc 'isfinite' not supported for the inpu...

โจทย์ปัญหาที่ 7: ลบคอลัมน์ที่ผลรวมเป็นลบทิ้ง

In [ ]:
def remove_neg_sum_cols(array: np.ndarray) -> np.ndarray:
    # เขียนโค้ดของคุณตรงนี้
    if array.sum <0:
      dataframe = dataframe.drop('C1', axis=1)
      df.drop(['C1'], axis=1, inplace=True)

In [ ]:
%%ipytest -qqs
def test_remove_neg_sum_cols():
    np.testing.assert_equal(
        remove_neg_sum_cols(np.array([
            [ 3,  2, -6, -3, -6],
            [-3, -5,  1,  3, -5],
            [ 3,  2,  2, -1,  2],
            [-3,  1, -5, -1, -3],
        ])),
        np.array([
            [ 3,  2],
            [-3, -5],
            [ 3,  2],
            [-3,  1],
        ]),
    )
    np.testing.assert_equal(
        remove_neg_sum_cols(np.array([
            [ -5, -12,  -9,  -6],
            [-15,   2,   2,  -9],
            [-11,  -7, -15,   4],
        ])),
        np.array([[], [], []]),
    )
    np.testing.assert_equal(
        remove_neg_sum_cols(np.array([
            [ 0,  3,  3,  1],
            [ 4,  0,  3, -2],
            [-1,  2,  4,  3],
        ])),
        np.array([
            [ 0,  3,  3,  1],
            [ 4,  0,  3, -2],
            [-1,  2,  4,  3],
        ]),
    )
    np.testing.assert_equal(
        remove_neg_sum_cols(np.array([
            [ 7,  2, -6],
            [ 3, -8, -4],
            [-4, -9, -4],
            [-6, 13, 15],
        ])),
        np.array([
            [ 7, -6],
            [ 3, -4],
            [-4, -4],
            [-6, 15],
        ]),
    )
    print("==== Test OK ====")

F
============================================= FAILURES =============================================
_____________________________________ test_remove_neg_sum_cols _____________________________________

    def test_remove_neg_sum_cols():
        np.testing.assert_equal(
            remove_neg_sum_cols(np.array([
                [ 3,  2, -6, -3, -6],
                [-3, -5,  1,  3, -5],
                [ 3,  2,  2, -1,  2],
>               [-3,  1, -5, -1, -3],
            ])),
            np.array([
                [ 3,  2],
                [-3, -5],
                [ 3,  2],
                [-3,  1],
            ]),
        )

<ipython-input-143-1a0f7ecce1b4>:7:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

array = array([[ 3,  2, -6, -3, -6],
       [-3, -5,  1,  3, -5],
       [ 3,  2,  2, -1,  2],
       [-3,  1, -5, -1, -3]])

    def remove_neg_sum_cols(array: np.ndarray) -> np.ndarray:
        # เขียนโค้ดของคุณตรงนี้
>       if array.sum <0:
E       TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'int'

<ipython-input-142-f28bc63e9e5e>:3: TypeError
===================================== short test summary info ======================================
FAILED tmp3kgo9hfl.py::test_remove_neg_sum_cols - TypeError: '<' not supported between instances ...

โจทย์ปัญหาที่ 8: ลบค่าทุกตัวด้วยจำนวนที่น้อยที่สุดในแต่ละแถวนั้น ๆ

In [ ]:
def subtract_by_row_min(array: np.ndarray) -> np.ndarray:
    # เขียนโค้ดของคุณตรงนี้
    for array.min in subtract_by_row_min(array: np.ndarray):
      subtract_by_row_min(array: np.ndarray) - array.min

SyntaxError: ignored

In [ ]:
%%ipytest -qqs
def test_subtract_by_row_min():
    np.testing.assert_equal(
        subtract_by_row_min(np.array([
            [ 48,  54,  79, -22, -23],
            [-72, -39,  45, -21, -53],
            [100,  62, -74,   0,  95],
            [ 99,  -2,  58,  12,  60],
        ])),
        np.array([
            [ 71,  77, 102,   1,   0],
            [  0,  33, 117,  51,  19],
            [174, 136,   0,  74, 169],
            [101,   0,  60,  14,  62],
        ]),
    )
    np.testing.assert_equal(
        subtract_by_row_min(np.array([
            [16, 70, 24, -9],
            [90, 76, 49, 91],
            [65, 72, 80, 55],
        ])),
        np.array([
            [25, 79, 33,  0],
            [41, 27,  0, 42],
            [10, 17, 25,  0],
        ]),
    )
    np.testing.assert_equal(
        subtract_by_row_min(np.array([
            [241, 319, 241],
            [254, 266, 118],
        ])),
        np.array([
            [  0,  78,   0],
            [136, 148,   0],
        ]),
    )
    print("==== Test OK ====")

F
============================================= FAILURES =============================================
_____________________________________ test_subtract_by_row_min _____________________________________

    def test_subtract_by_row_min():
        np.testing.assert_equal(
>           subtract_by_row_min(np.array([
                [ 48,  54,  79, -22, -23],
                [-72, -39,  45, -21, -53],
                [100,  62, -74,   0,  95],
                [ 99,  -2,  58,  12,  60],
            ])),
            np.array([
                [ 71,  77, 102,   1,   0],
                [  0,  33, 117,  51,  19],
                [174, 136,   0,  74, 169],
                [101,   0,  60,  14,  62],
            ]),
        )
E       NameError: name 'subtract_by_row_min' is not defined

<ipython-input-145-c84ca242f710>:3: NameError
===================================== short test summary info ======================================
FAILED tmpxmxw4nk9.py::test_subtract_by_row_min - NameError: name 'subtract_by_row_min' is not de...

ข้อมูลงานกีฬาสีของนักเรียนมัธยม

โจทย์ปัญหาที่ 9: นามสกุลที่โหลที่สุด

In [ ]:
SPORTSDAY_DF = pd.read_csv('sportsday.csv')  # โหลดข้อมูลจากไฟล์
display(SPORTSDAY_DF.head(10))  # ตัวอย่างข้อมูล 10 แถวแรก
display(SPORTSDAY_DF.tail(10))  # ตัวอย่างข้อมูล 10 แถวสุดท้าย

,first_name,last_name,class,team_color,100m_running_sec,minigolf_strokes,high_jump_cm,bowling_score
0,Ryan,Allen,8,whale_blue,16.85,24,69.65,135
1,Kathleen,Gomez,7,duckling_yellow,12.22,29,121.28,51
2,Anthony,Nguyen,8,salmon_red,18.58,50,89.77,201
3,William,Hill,9,whale_blue,16.75,57,64.31,254
4,Dorothy,Gonzales,12,caterpillar_green,14.35,55,115.82,81
5,Steven,Lewis,8,salmon_red,19.70,42,89.91,22
6,Richard,Miller,7,duckling_yellow,18.70,54,106.12,240
7,Lisa,Campbell,9,duckling_yellow,19.91,70,98.93,278
8,Justin,Brown,7,duckling_yellow,12.00,32,102.99,157
9,Carol,Allen,10,duckling_yellow,15.15,69,109.31,121

,first_name,last_name,class,team_color,100m_running_sec,minigolf_strokes,high_jump_cm,bowling_score
190,Angela,Moore,10,salmon_red,15.61,21,70.88,71
191,Amanda,Wilson,11,salmon_red,14.82,55,62.54,37
192,Shirley,Gonzales,8,caterpillar_green,16.36,68,93.90,228
193,Stephanie,Rodriguez,12,whale_blue,14.20,65,102.90,31
194,Andrew,Gonzales,8,whale_blue,15.95,36,81.61,222
195,Michael,Martinez,12,duckling_yellow,17.93,44,92.19,30
196,Paul,Martinez,8,whale_blue,11.41,33,115.60,188
197,Nicole,Baker,9,whale_blue,17.98,66,71.17,151
198,Helen,Davis,8,caterpillar_green,11.64,46,96.10,43
199,Joseph,Hill,10,caterpillar_green,13.63,42,71.90,251

In [ ]:
def common_last_name(df: pd.DataFrame) -> str:
    # เขียนโค้ดของคุณตรงนี้
    ...

In [ ]:
%%ipytest -qqs
def test_common_last_name():
    assert common_last_name(SPORTSDAY_DF) == 8
    assert common_last_name(SPORTSDAY_DF[SPORTSDAY_DF.team_color == 'salmon_red']) == 4
    assert common_last_name(SPORTSDAY_DF[SPORTSDAY_DF['class'] == 7]) == 3
    print("==== Test OK ====")

F
============================================= FAILURES =============================================
______________________________________ test_common_last_name _______________________________________

    def test_common_last_name():
>       assert common_last_name(SPORTSDAY_DF) == 8
E       assert None == 8
E        +  where None = common_last_name(    first_name last_name  class         team_color  100m_running_sec  \\n0         Ryan     Allen      8         whale_...         46         96.10             43  \n199                42         71.90            251  \n\n[200 rows x 8 columns])

<ipython-input-148-6dae538f70a4>:2: AssertionError
===================================== short test summary info ======================================
FAILED tmprhutjrki.py::test_common_last_name - assert None == 8

โจทย์ปัญหาที่ 10: นักวิ่งลมกรดประจำทีม

In [ ]:
def fast_runners(df: pd.DataFrame, team_color: str, max_running_time: float) -> pd.DataFrame:
    # เขียนโค้ดของคุณตรงนี้
    ...

In [ ]:
%%ipytest -qqs
def test_fast_runners():
    result = fast_runners(SPORTSDAY_DF, 'salmon_red', 12.0)
    pd.testing.assert_index_equal(result.columns, SPORTSDAY_DF.columns)
    assert set(result[['first_name', 'last_name']].itertuples(index=False, name=None)) == {
        ('Angela', 'Williams'),
        ('Emily', 'Flores'),
        ('Gary', 'Martinez'),
        ('Jason', 'Scott'),
        ('Justin', 'Lopez'),
    }
    
    result = fast_runners(SPORTSDAY_DF, 'caterpillar_green', 11.5)
    pd.testing.assert_index_equal(result.columns, SPORTSDAY_DF.columns)
    assert set(result[['first_name', 'last_name']].itertuples(index=False, name=None)) == {
        ('Daniel', 'Rodriguez'), 
        ('Kathleen', 'Edwards'), 
        ('Linda', 'Turner'),
    }
    
    result = fast_runners(SPORTSDAY_DF, 'whale_blue', 11.0)
    pd.testing.assert_index_equal(result.columns, SPORTSDAY_DF.columns)
    assert set(result[['first_name', 'last_name']].itertuples(index=False, name=None)) == set()
    
    print("==== Test OK ====")

โจทย์ปัญหาที่ 11: สถิติโบวลิ่งและมินิกอล์ฟประจำชั้น

In [ ]:
def best_bowling_and_minigolf(df: pd.DataFrame, class_no: int) -> tuple[float, float]:
    # เขียนโค้ดของคุณตรงนี้
    ...

In [ ]:
%%ipytest -qqs
def test_best_bowling_and_minigolf():
    assert best_bowling_and_minigolf(SPORTSDAY_DF, 8) == (291, 18)
    assert best_bowling_and_minigolf(SPORTSDAY_DF, 10) == (284, 21)
    assert best_bowling_and_minigolf(SPORTSDAY_DF, 12) == (300, 18)
    print("==== Test OK ====")

โจทย์ปัญหาที่ 12: ค่าเฉลี่ยการกระโดดสูง

In [ ]:
def highjump_averages(df: pd.DataFrame) -> pd.Series:
    # เขียนโค้ดของคุณตรงนี้
    ...

In [ ]:
%%ipytest -qqs
def test_best_bowling_and_minigolf():
    assert highjump_averages(SPORTSDAY_DF).to_dict() == approx({
        'caterpillar_green': 93.21265306122449,
        'duckling_yellow': 98.88854166666665,
        'salmon_red': 89.11403846153847,
        'whale_blue': 93.18333333333334,
    })
    assert highjump_averages(SPORTSDAY_DF[SPORTSDAY_DF['class'] == 9]).to_dict() == approx({
        'caterpillar_green': 103.64555555555555,
        'duckling_yellow': 100.98625,
        'salmon_red': 83.57,
        'whale_blue': 90.29,
    })
    assert highjump_averages(SPORTSDAY_DF[SPORTSDAY_DF['class'].isin([7, 11])]).to_dict() == approx({
        'caterpillar_green': 87.44583333333333,
        'duckling_yellow': 101.9042105263158,
        'salmon_red': 90.19999999999999,
        'whale_blue': 96.38307692307693,
    })
    print("==== Test OK ====")